create database Car_rental;
use Car_rental;
-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888 
-- at: 2023-10-21 20:51:30 PKT 
-- site: Oracle Database 11g 
-- type: Oracle Database 11g

CREATE TABLE Car 
( 
  Reg_no VARCHAR(20) NOT NULL , 
  C_name VARCHAR(50) NOT NULL , 
  Model INTEGER NOT NULL , 
  Available CHAR(1) NOT NULL , 
  Descripton VARCHAR(4000) NOT NULL , 
  Price_Per_Day INTEGER NOT NULL , 
  Transmission VARCHAR(20) NOT NULL , 
  Mileage INTEGER NOT NULL , 
  Int_img VARCHAR(4000) NOT NULL , 
  Ext_img VARCHAR(4000) NOT NULL , 
  Reg_Year VARCHAR(4) NOT NULL , 
  Color VARCHAR(50) NOT NULL , 
  Owner_O_id VARCHAR(20) NOT NULL,
  Doors INTEGER,
     Passengers INTEGER,
     Luggage INTEGER
) ;
select * from car;

ALTER TABLE Car ADD CONSTRAINT Car_PK PRIMARY KEY (Reg_no) ;


CREATE TABLE Car_Registration 
( 
  CR_id VARCHAR(20) NOT NULL , 
  Car_Reg_no VARCHAR(20) NOT NULL 
) ;

ALTER TABLE Car_Registration ADD CONSTRAINT Car_Registration_PK PRIMARY KEY (CR_id) ;


CREATE TABLE Customer 
( 
  Cus_id VARCHAR(20) NOT NULL , 
  Name VARCHAR(50) NOT NULL , 
  Address VARCHAR(4000) NOT NULL , 
  ph_Number VARCHAR(13) NOT NULL , 
  Age INTEGER NOT NULL , 
  Zip_code INTEGER NOT NULL , 
  Gender VARCHAR(1) NOT NULL 
) ;

ALTER TABLE Customer ADD CONSTRAINT Customer_PK PRIMARY KEY (Cus_id) ;


CREATE TABLE Owner 
( 
  O_id VARCHAR(20) NOT NULL , 
  Name VARCHAR(50) NOT NULL , 
  Address VARCHAR(4000) NOT NULL , 
  ph_Number VARCHAR(13) NOT NULL , 
  Gender VARCHAR(1) NOT NULL 
) ;

ALTER TABLE Owner ADD CONSTRAINT Owner_PK PRIMARY KEY (O_id) ;


CREATE TABLE Rental_Reg 
( 
  Reg_id VARCHAR(20) NOT NULL , 
  Days INTEGER NOT NULL , 
  Commision INTEGER NOT NULL , 
  Total_Price INTEGER NOT NULL , 
  Pick_up_TD TIMESTAMP NOT NULL , 
  Drop_off_TD TIMESTAMP NOT NULL , 
  Customer_Cus_id VARCHAR(20) NOT NULL , 
  Car_Reg_no VARCHAR(20) NOT NULL 
) ;



ALTER TABLE Rental_Reg ADD CONSTRAINT Rental_Reg_PK PRIMARY KEY (Reg_id) ;

drop table Transactions;
CREATE TABLE Transactions (
  T_id VARCHAR(20) NOT NULL,
  Rental_Reg_Reg_id VARCHAR(20) UNIQUE,
  FOREIGN KEY (Rental_Reg_Reg_id) REFERENCES Rental_Reg(Reg_id)
);



ALTER TABLE Transactions ADD CONSTRAINT Transactions_PK PRIMARY KEY (T_id) ;


ALTER TABLE Car ADD CONSTRAINT Car_Owner_FK FOREIGN KEY (Owner_O_id) 
REFERENCES Owner (O_id) ;

ALTER TABLE Car_Registration ADD CONSTRAINT Car_Registration_Car_FK FOREIGN KEY (Car_Reg_no) 
REFERENCES Car (Reg_no) ;


ALTER TABLE Rental_Reg ADD CONSTRAINT Rental_Reg_Car_FK FOREIGN KEY (Car_Reg_no) 
REFERENCES Car (Reg_no) ;

ALTER TABLE Rental_Reg ADD CONSTRAINT Rental_Reg_Customer_FK FOREIGN KEY (Customer_Cus_id) 
REFERENCES Customer (Cus_id) ;



-- Insert one owner
INSERT INTO Owner (O_id, Name, Address, ph_Number, Gender)
VALUES ('O001', 'AK_Rental', '123 Main St', '1234567890', 'M');
-- Insert cars
INSERT INTO Car (Reg_no, C_name, Model, Available, Descripton, Price_Per_Day, Transmission, Mileage, Int_img, Ext_img, Reg_Year, Color, Owner_O_id)
VALUES 
  ('CAR001', 'Civic', 2022, 'Y', 'Civic description', 50, 'Automatic', 25, 'int_civic_img.jpg', 'ext_civic_img.jpg', '2022', 'Red', 'O001'),
  ('CAR002', 'Fortuner', 2022, 'Y', 'Fortuner description', 70, 'Automatic', 18, 'int_fortuner_img.jpg', 'ext_fortuner_img.jpg', '2022', 'Black', 'O001'),
  ('CAR003', 'Alto', 2022, 'Y', 'Alto description', 30, 'Manual', 30, 'int_alto_img.jpg', 'ext_alto_img.jpg', '2022', 'White', 'O001'),
  ('CAR004', 'Audi A4', 2022, 'Y', 'Audi A4 description', 90, 'Automatic', 22, 'int_audi_img.jpg', 'ext_audi_img.jpg', '2022', 'Silver', 'O001'),
  ('CAR005', 'Civic', 2022, 'Y', 'Civic description', 50, 'Automatic', 25, 'int_civic_img.jpg', 'ext_civic_img.jpg', '2022', 'Red', 'O001'),
  ('CAR006', 'Fortuner', 2022, 'Y', 'Fortuner description', 70, 'Automatic', 18, 'int_fortuner_img.jpg', 'ext_fortuner_img.jpg', '2022', 'Black', 'O001'),
  ('CAR007', 'Alto', 2022, 'Y', 'Alto description', 30, 'Manual', 30, 'int_alto_img.jpg', 'ext_alto_img.jpg', '2022', 'White', 'O001'),
  ('CAR008', 'Audi A4', 2022, 'Y', 'Audi A4 description', 90, 'Automatic', 22, 'int_audi_img.jpg', 'ext_audi_img.jpg', '2022', 'Silver', 'O001'),
  ('CAR009', 'Civic', 2022, 'Y', 'Civic description', 50, 'Automatic', 25, 'int_civic_img.jpg', 'ext_civic_img.jpg', '2022', 'Red', 'O001'),
  ('CAR010', 'Fortuner', 2022, 'Y', 'Fortuner description', 70, 'Automatic', 18, 'int_fortuner_img.jpg', 'ext_fortuner_img.jpg', '2022', 'Black', 'O001');

-- Insert car registrations
INSERT INTO Car_Registration (CR_id, Car_Reg_no)
VALUES
  ('CR001', 'CAR001'),
  ('CR002', 'CAR002'),
  ('CR003', 'CAR003'),
  ('CR004', 'CAR004'),
  ('CR005', 'CAR005'),
  ('CR006', 'CAR006'),
  ('CR007', 'CAR007'),
  ('CR008', 'CAR008'),
  ('CR009', 'CAR009'),
  ('CR010', 'CAR010');
  
  ALTER TABLE Car 
ADD (Doors INTEGER,
     Passengers INTEGER,
     Luggage INTEGER);

-- Updating Car table with new attributes
UPDATE Car 
SET Doors = 4, Passengers = 5, Luggage = 2
WHERE Reg_no IN ('CAR001', 'CAR002', 'CAR003', 'CAR004', 'CAR005', 'CAR006', 'CAR007', 'CAR008', 'CAR009', 'CAR010');

  
update Car C join  Rental_Reg R on C.reg_no =R.car_reg_no
set C.available= 'Y' where R.car_reg_no=reg_no and R.drop_off_TD <=CURRENT_TIMESTAMP;

select * from Car;

select * from Rental_Reg;
DELETE FROM transactions WHERE T_id LIKE '%' LIMIT 1000;
DELETE FROM Rental_Reg WHERE Reg_id LIKE '%' LIMIT 1000;
DELETE FROM Customer WHERE Cus_id LIKE '%' LIMIT 1000;






